# Understand the data

@author : Eva MAROT

@id : 20220929

In [270]:
import pandas as pd

In [271]:
AIR_QUALITY_PATH = "data/air_quality.csv" 
GTFS_ZIP_PATH = "data/IDFM-gtfs.zip"

Air quality data

In [272]:
air_df_raw = pd.read_csv(AIR_QUALITY_PATH, sep=';', encoding='utf-8')

In [273]:
air_df_raw

,Identifiant station,Nom de la Station,Nom de la ligne,Niveau de pollution aux particules,Niveau de pollution,Incertitude,Recommandation de surveillance,Action(s) QAI en cours,Lien vers les mesures en direct,Durée des mesures,Mesures d’amélioration mises en place ou prévues,stop_lon,stop_lat,point_geo,pollution_air,air,niveau,actions,niveau_pollution
0,IDFM:463116,Abbesses,Métro 12,pollution faible,FAIBLE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.338395,48.884393,"48.884392717991425, 2.338394635220906",pollution faible - incertitude forte,NaN,Pollution faible,NaN,pollution faible
1,IDFM:483900,Aimé Césaire,Métro 12,pollution faible,FAIBLE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.378131,48.908438,"48.90843758066954, 2.37813084516706",pollution faible - incertitude forte,NaN,Pollution faible,NaN,pollution faible
2,IDFM:monomodalStopPlace:46395,Athis-Mons,RER C,station aérienne,station aérienne,NaN,non,NaN,https://www.airparif.fr/,NaN,NaN,2.403669,48.712668,"48.71266832171659, 2.403668724287269",station aérienne,NaN,Station aérienne – Proche des niveaux en air e...,NaN,station aérienne
3,IDFM:22130,Barbès - Rochechouart,Métro 4,pollution faible,FAIBLE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.349630,48.883402,"48.883402060486226, 2.349629927853002",pollution faible - incertitude forte,NaN,Pollution faible,NaN,pollution faible
4,IDFM:463019,Bastille,Métro 1,pollution moyenne,MOYENNE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.368693,48.851964,"48.85196422011205, 2.368692796099789",pollution moyenne - incertitude forte,NaN,Pollution moyenne,NaN,pollution moyenne
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,IDFM:463320,Varenne,Métro 13,pollution moyenne,MOYENNE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.314978,48.856624,"48.85662420264694, 2.3149776470363417",pollution moyenne - incertitude forte,NaN,Pollution moyenne,NaN,pollution moyenne
658,IDFM:463321,Vaugirard,Métro 12,pollution faible,FAIBLE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.300978,48.839536,"48.83953628376544, 2.300977822126098",pollution faible - incertitude forte,NaN,Pollution faible,NaN,pollution faible
659,IDFM:monomodalStopPlace:43223,Villiers-sur-Marne - Le Plessis-Trévise,RER E,station aérienne,station aérienne,NaN,non,NaN,https://www.airparif.fr/,NaN,NaN,2.542644,48.823248,"48.82324786783017, 2.542644466674205",station aérienne,NaN,Station aérienne – Proche des niveaux en air e...,NaN,station aérienne
660,IDFM:monomodalStopPlace:46375,Vitry-sur-Seine,RER C,station aérienne,station aérienne,NaN,non,NaN,https://www.airparif.fr/,NaN,NaN,2.402694,48.800281,"48.80028105254759, 2.40269438767449",station aérienne,NaN,Station aérienne – Proche des niveaux en air e...,NaN,station aérienne
661,IDFM:463070,Wagram,Métro 3,pollution moyenne,MOYENNE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.304673,48.883846,"48.8838463907272, 2.304673087584434",pollution moyenne - incertitude forte,NaN,Pollution moyenne,NaN,pollution moyenne

In [274]:
air_df_raw = air_df_raw.rename(columns={
    'Identifiant station': 'station_id',
    'Nom de la Station': 'station_name',
    'Nom de la ligne': 'line_name',
    'Niveau de pollution aux particules': 'pollution_level_text',
    'stop_lat': 'stop_lat_air',
    'stop_lon': 'stop_lon_air',
})
air_df_raw.head(3)

,station_id,station_name,line_name,pollution_level_text,Niveau de pollution,Incertitude,Recommandation de surveillance,Action(s) QAI en cours,Lien vers les mesures en direct,Durée des mesures,Mesures d’amélioration mises en place ou prévues,stop_lon_air,stop_lat_air,point_geo,pollution_air,air,niveau,actions,niveau_pollution
0,IDFM:463116,Abbesses,Métro 12,pollution faible,FAIBLE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.338395,48.884393,"48.884392717991425, 2.338394635220906",pollution faible - incertitude forte,NaN,Pollution faible,NaN,pollution faible
1,IDFM:483900,Aimé Césaire,Métro 12,pollution faible,FAIBLE,Évaluation : modélisation reposant notamment s...,non,NaN,NaN,NaN,NaN,2.378131,48.908438,"48.90843758066954, 2.37813084516706",pollution faible - incertitude forte,NaN,Pollution faible,NaN,pollution faible
2,IDFM:monomodalStopPlace:46395,Athis-Mons,RER C,station aérienne,station aérienne,NaN,non,NaN,https://www.airparif.fr/,NaN,NaN,2.403669,48.712668,"48.71266832171659, 2.403668724287269",station aérienne,NaN,Station aérienne – Proche des niveaux en air e...,NaN,station aérienne

In [275]:
air_df_raw.shape

(662, 19)

In [276]:
#delete columns Niveau de pollution, Incertitude, Recommandation de surveillance, Action(s) QAI en cours, Lien vers les mesures en direct, Durée des mesures, Mesures d’amélioration mises en place ou prévues, point_geo, air, niveau, actions, niveau_pollution
air_df_raw.drop(columns=['Niveau de pollution', 'Incertitude', 'Recommandation de surveillance', 'Action(s) QAI en cours', 'Lien vers les mesures en direct', 'Durée des mesures', "Mesures d’amélioration mises en place ou prévues", 'point_geo', 'pollution_air', 'air', 'niveau', 'actions', 'niveau_pollution'], inplace=True)
air_df_raw.head(3)

,station_id,station_name,line_name,pollution_level_text,stop_lon_air,stop_lat_air
0,IDFM:463116,Abbesses,Métro 12,pollution faible,2.338395,48.884393
1,IDFM:483900,Aimé Césaire,Métro 12,pollution faible,2.378131,48.908438
2,IDFM:monomodalStopPlace:46395,Athis-Mons,RER C,station aérienne,2.403669,48.712668

In [277]:
df_air_processed = air_df_raw.copy()

Scheduled times for public transportation lines in the Ile-de-France region dataset

In [278]:
import zipfile

print("\n--- GTFS Data Loading and Exploration ---")

gtfs_data_raw = {}
try:
    with zipfile.ZipFile(GTFS_ZIP_PATH, 'r') as z:
        gtfs_data_raw = {
            'stops': pd.read_csv(z.open('stops.txt')),
            'stop_times': pd.read_csv(z.open('stop_times.txt')),
            'trips': pd.read_csv(z.open('trips.txt')),
            'routes': pd.read_csv(z.open('routes.txt'))
        }
    print("GTFS Data loaded successfully (stops, stop_times, trips).")
    
except Exception as e:
    print(f"ERROR loading GTFS data. Check ZIP path or file names inside the zip: {e}")
    gtfs_data_raw = {}

--- GTFS Data Loading and Exploration ---

C:\Users\eva2p\AppData\Local\Temp\ipykernel_10900\3830170247.py:10: DtypeWarning: Columns (12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  'stop_times': pd.read_csv(z.open('stop_times.txt')),

GTFS Data loaded successfully (stops, stop_times, trips).

C:\Users\eva2p\AppData\Local\Temp\ipykernel_10900\3830170247.py:11: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  'trips': pd.read_csv(z.open('trips.txt')),

In [279]:
if 'stops' in gtfs_data_raw:
    df_stops = gtfs_data_raw['stops']
    print("\n### GTFS Stops Data (Location Data - Merge Key & Geo)")
    print(f"Shape: {df_stops.shape}")
    print("Columns of Interest (Head):")
    # Columns of interest: stop_id (for internal GTFS merge), stop_name (for Air Quality merge), stop_lat, stop_lon (for map)
    print(df_stops[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']].head(3))
    print("-" * 20)

### GTFS Stops Data (Location Data - Merge Key & Geo)
Shape: (53657, 14)
Columns of Interest (Head):
                          stop_id            stop_name   stop_lat  stop_lon
0  IDFM:monomodalStopPlace:473875               Nation  48.848233  2.395944
1   IDFM:monomodalStopPlace:53783     Chatou - Croissy  48.885197  2.155938
2   IDFM:monomodalStopPlace:53784  Le Vésinet - Centre  48.890138  2.134334
--------------------

In [280]:
if 'stop_times' in gtfs_data_raw:
    df_stop_times = gtfs_data_raw['stop_times']
    print("\n### GTFS Stop Times Data (Schedule Data - Frequency Calculation)")
    print(f"Shape: {df_stop_times.shape}")
    print("Columns of Interest (Head):")
    # Columns of interest: trip_id (to link to trips), arrival_time (for hour extraction), stop_id (to link to stops)
    print(df_stop_times[['trip_id', 'arrival_time', 'stop_id']].head(3))
    print("-" * 20)

### GTFS Stop Times Data (Schedule Data - Frequency Calculation)
Shape: (10275854, 14)
Columns of Interest (Head):
                                             trip_id arrival_time      stop_id
0  IDFM:RATP:146151-C01385-COU_RATP_388795_313948_65     08:10:00  IDFM:463175
1  IDFM:RATP:146151-C01385-COU_RATP_388795_313948_65     08:15:00  IDFM:412355
2                 IDFM:stif:local-175995-C00562-5491     12:02:00   IDFM:10228
--------------------

In [281]:
if 'routes' in gtfs_data_raw:
    df_routes = gtfs_data_raw['routes']
    print("\n### GTFS Routes Data (Line Names)")
    print(f"Shape: {df_routes.shape}")
    print("Columns of Interest (Head):")
    # Columns of interest: route_id (for internal GTFS merge with trips), route_short_name, route_long_name
    print(df_routes[['route_id', 'route_short_name', 'route_long_name']].head(3))

### GTFS Routes Data (Line Names)
Shape: (2004, 10)
Columns of Interest (Head):
      route_id route_short_name route_long_name
0  IDFM:C01624             4244            4244
1  IDFM:C02313             5310            5310
2  IDFM:C00029              502             502

In [282]:
if 'trips' in gtfs_data_raw:
    df_trips = gtfs_data_raw['trips']
    print("\n### GTFS Trips Data (Link Schedules to Routes)")
    print(f"Shape: {df_trips.shape}")
    print("Columns of Interest (Head):")
    
    # Columns of interest: 
    # route_id (to link to routes.txt for line name)
    # trip_id (to link to stop_times.txt for schedule/frequency calculation)
    # service_id (to link to calendar.txt, though we can skip filtering by service for now)
    
    # We check for the three most critical columns for our merge logic
    print(df_trips[['route_id', 'trip_id', 'service_id']].head(3))
    print("-" * 20)

### GTFS Trips Data (Link Schedules to Routes)
Shape: (461280, 10)
Columns of Interest (Head):
      route_id                                            trip_id service_id
0  IDFM:C01385  IDFM:RATP:146151-C01385-COU_RATP_388795_313948_65     IDFM:1
1  IDFM:C00562                 IDFM:stif:local-175995-C00562-5491     IDFM:1
2  IDFM:C00562                 IDFM:stif:local-175995-C00562-5439     IDFM:1
--------------------

In [283]:
import numpy as np
def process_gtfs(gtfs_data):
    """
    Cleans and merges GTFS data to calculate the average passage frequency 
    for each station, and extracts the line name.
    
    Outputs: DataFrame with ['station_name', 'line_name', 'stop_lat', 'stop_lon', 'avg_passages']
    """
    
    df_stops = gtfs_data['stops']
    df_stop_times = gtfs_data['stop_times']
    df_trips = gtfs_data['trips']
    df_routes = gtfs_data['routes']

    # --- 1. Link Trips to Routes to get the Line Name ---
    # Merge trips and routes on 'route_id'
    df_trips_routes = df_trips[['route_id', 'trip_id']].merge(
        df_routes[['route_id', 'route_short_name', 'route_long_name']],
        on='route_id',
        how='left'
    )
    
    # Prioritize the short name for the line name
    df_trips_routes['line_name_clean'] = df_trips_routes['route_short_name'].fillna(df_trips_routes['route_long_name']).astype(str)
    
    # Filter to keep only the necessary columns
    df_trips_routes = df_trips_routes[['trip_id', 'line_name_clean']]


    # --- 2. Calculate Passages Count per Stop and Hour ---
    
    # 2a. Time conversion function (handling 24+ hour format)
    def time_to_hour(time_str):
        try:
            h, m, s = map(int, time_str.split(':'))
            return h * 3600 + m * 60 + s # Total seconds from midnight
        except:
            return np.nan
            
    df_stop_times['arrival_time_sec'] = df_stop_times['arrival_time'].apply(time_to_hour)
    df_stop_times.dropna(subset=['arrival_time_sec'], inplace=True)
    
    # 2b. Extract Hour (0-23)
    # Use modulo 24 to get a standard hour of day (0-23)
    df_stop_times['hour'] = (df_stop_times['arrival_time_sec'] // 3600).astype(int) % 24 

    # 2c. Link stop_times to trip_routes to know the line for each passage
    df_frequency_raw = df_stop_times.merge(df_trips_routes, on='trip_id', how='left')
    df_frequency_raw.dropna(subset=['line_name_clean'], inplace=True) # Drop passages we can't link to a line
    
    # 2d. Count passages per stop, per hour, per line
    df_frequency = df_frequency_raw.groupby(['stop_id', 'line_name_clean', 'hour']).size().reset_index(name='passages_count')


    # --- 3. Final Aggregation and Normalization ---
    
    # 3a. Merge with 'stops' for station names and coordinates
    df_stops_clean = df_stops[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']].copy()
    
    # 3b. Normalize station names (CRUCIAL FOR AIR QUALITY JOIN)
    df_stops_clean.rename(columns={'stop_name': 'station_name'}, inplace=True)
    df_stops_clean['station_name'] = df_stops_clean['station_name'].str.lower().str.strip() 

    # 3c. Calculate Average Frequency per Station across all hours/lines
    # We calculate the average frequency of all lines going through a single stop_id
    df_final_gtfs = df_frequency.merge(df_stops_clean, on='stop_id', how='left')
    
    df_station_avg_freq = df_final_gtfs.groupby(['station_name']).agg(
        stop_lat=('stop_lat', 'first'),
        stop_lon=('stop_lon', 'first'),
        avg_passages=('passages_count', 'mean'), # Average frequency score
        line_name=('line_name_clean', lambda x: ', '.join(x.unique())) # List all lines serving the station
    ).reset_index()

    return df_station_avg_freq

In [284]:
# Assuming gtfs_data_raw was loaded in a previous cell

print("--- Processing GTFS data... This may take a moment due to the large size (10M+ rows) ---")
df_gtfs_processed = process_gtfs(gtfs_data_raw)

print("--- Processed GTFS Data Check ---")
print(f"Shape: {df_gtfs_processed.shape}")
print(f"Columns: {df_gtfs_processed.columns.tolist()}")

# Check the cleaned station name, coordinates, and the calculated frequency
print("\nSample (Check Clean Name, Geo, and Avg Frequency):")
print(df_gtfs_processed.head())

# Check extreme values
print("\nStations with the highest average traffic frequency:")
print(df_gtfs_processed.sort_values(by='avg_passages', ascending=False).head())

--- Processing GTFS data... This may take a moment due to the large size (10M+ rows) ---
--- Processed GTFS Data Check ---
Shape: (13568, 5)
Columns: ['station_name', 'stop_lat', 'stop_lon', 'avg_passages', 'line_name']

Sample (Check Clean Name, Geo, and Avg Frequency):
                                station_name   stop_lat  stop_lon  \
0                          1 route nationale  48.805000  1.774690
1                                 10 arpents  49.040531  2.309446
2                                11 novembre  48.880673  2.493969
3  11 novembre - gare de coucelle-sur-yvette  48.703764  2.107537
4                           11 novembre 1918  48.892935  2.465999

   avg_passages                                          line_name
0      1.460000                             5332, 5338, 5342, 5367
1      2.129032                                1520, Navette, Soir
2     11.655319  221, 214, 3432, Soir, 114, 4531, 4534, 2, 612,...
3      4.636364                                               N122
4     15.484429  105, 143, 208, 308, N33, 181, 2304, 2302, 2374...

Stations with the highest average traffic frequency:
                  station_name   stop_lat  stop_lon  avg_passages line_name
13190                vincennes  48.847347  2.432584    218.800000         A
1255            bourg-la-reine  48.780264  2.312278    206.190476         B
12078  saint-michel notre-dame  48.853024  2.344960    199.100000      B, C
2298       châtelet les halles  48.861745  2.346977    190.475410   A, B, D
8982       nanterre préfecture  48.895887  2.222986    190.142857         A

In [285]:
df_gtfs_processed

,station_name,stop_lat,stop_lon,avg_passages,line_name
0,1 route nationale,48.805000,1.774690,1.460000,"5332, 5338, 5342, 5367"
1,10 arpents,49.040531,2.309446,2.129032,"1520, Navette, Soir"
2,11 novembre,48.880673,2.493969,11.655319,"221, 214, 3432, Soir, 114, 4531, 4534, 2, 612,..."
3,11 novembre - gare de coucelle-sur-yvette,48.703764,2.107537,4.636364,N122
4,11 novembre 1918,48.892935,2.465999,15.484429,"105, 143, 208, 308, N33, 181, 2304, 2302, 2374..."
...,...,...,...,...,...
13563,île saint-louis,48.851673,2.356322,11.578947,67
13564,île verte,48.895978,2.163263,4.350000,"12, S3, T"
13565,île-de-france,48.685936,2.169871,14.973054,"4602, 4603, 4627, 4654, 203, 214, 303, 6533, 6..."
13566,île-de-loisirs,49.022372,2.055395,7.486486,1207
13567,îles glénan,48.767394,1.926243,2.558140,"5121, 5123, 5190, 5124"

Check duplicates

In [286]:
#duplicate count in air quality processed data
df_air_processed['station_name'].duplicated().sum()

np.int64(107)

In [287]:
df_air_processed[['station_name', 'line_name']].duplicated().sum()

np.int64(0)

In [288]:
#duplicate count in GTFS processed data
df_gtfs_processed['station_name'].duplicated().sum()

np.int64(0)

Check missing values

In [289]:
# check missing values in air quality processed data
df_air_processed.isnull().sum()

station_id              0
station_name            0
line_name               0
pollution_level_text    0
stop_lon_air            0
stop_lat_air            0
dtype: int64

In [290]:
# checlk missing values in GTFS processed data
df_gtfs_processed.isnull().sum()

station_name    0
stop_lat        0
stop_lon        0
avg_passages    0
line_name       0
dtype: int64

In [291]:
df_air_processed.dtypes

station_id               object
station_name             object
line_name                object
pollution_level_text     object
stop_lon_air            float64
stop_lat_air            float64
dtype: object

In [292]:
df_air_processed

,station_id,station_name,line_name,pollution_level_text,stop_lon_air,stop_lat_air
0,IDFM:463116,Abbesses,Métro 12,pollution faible,2.338395,48.884393
1,IDFM:483900,Aimé Césaire,Métro 12,pollution faible,2.378131,48.908438
2,IDFM:monomodalStopPlace:46395,Athis-Mons,RER C,station aérienne,2.403669,48.712668
3,IDFM:22130,Barbès - Rochechouart,Métro 4,pollution faible,2.349630,48.883402
4,IDFM:463019,Bastille,Métro 1,pollution moyenne,2.368693,48.851964
...,...,...,...,...,...,...
657,IDFM:463320,Varenne,Métro 13,pollution moyenne,2.314978,48.856624
658,IDFM:463321,Vaugirard,Métro 12,pollution faible,2.300978,48.839536
659,IDFM:monomodalStopPlace:43223,Villiers-sur-Marne - Le Plessis-Trévise,RER E,station aérienne,2.542644,48.823248
660,IDFM:monomodalStopPlace:46375,Vitry-sur-Seine,RER C,station aérienne,2.402694,48.800281
661,IDFM:463070,Wagram,Métro 3,pollution moyenne,2.304673,48.883846

In [293]:
# delete rows with pollution_level_text as "station aérienne"
df_air_processed = df_air_processed[df_air_processed['pollution_level_text'] != "station aérienne"]
df_air_processed

,station_id,station_name,line_name,pollution_level_text,stop_lon_air,stop_lat_air
0,IDFM:463116,Abbesses,Métro 12,pollution faible,2.338395,48.884393
1,IDFM:483900,Aimé Césaire,Métro 12,pollution faible,2.378131,48.908438
3,IDFM:22130,Barbès - Rochechouart,Métro 4,pollution faible,2.349630,48.883402
4,IDFM:463019,Bastille,Métro 1,pollution moyenne,2.368693,48.851964
5,IDFM:463110,Belleville,Métro 11,pollution moyenne,2.376685,48.871990
...,...,...,...,...,...,...
654,IDFM:22164,Trocadéro,Métro 6,pollution moyenne,2.287625,48.863461
656,IDFM:462959,Vaneau,Métro 10,pollution moyenne,2.321351,48.848895
657,IDFM:463320,Varenne,Métro 13,pollution moyenne,2.314978,48.856624
658,IDFM:463321,Vaugirard,Métro 12,pollution faible,2.300978,48.839536
661,IDFM:463070,Wagram,Métro 3,pollution moyenne,2.304673,48.883846

In [294]:
# Assuming df_air_cleaned is the DataFrame *after* removing 'station aérienne' rows.

print("\n--- Quantification of Pollution Score ---")

# Apply the mapping: convert pollution text to score (1, 2, or 3)
df_air_processed['pollution_score'] = df_air_processed['pollution_level_text'].str.lower().map(POLLUTION_SCORE_MAP)

# --- NOUVELLE ÉTAPE : Identifier les scores manquants ---
missing_score_stations = df_air_processed[df_air_processed['pollution_score'].isna()]

if not missing_score_stations.empty:
    print(f"WARNING: {len(missing_score_stations)} stations could not be assigned a pollution score.")
    print("These stations had the following text values:")
    # Affiche les valeurs uniques de 'pollution_level_text' qui n'ont pas pu être mappées
    print(missing_score_stations['pollution_level_text'].unique())
    print("\nStations with missing scores:")
    print(missing_score_stations[['station_name', 'line_name', 'pollution_level_text']].head()) # Affiche un échantillon
else:
    print("All underground stations were successfully assigned a pollution score.")
# --- FIN DE LA NOUVELLE ÉTAPE ---

# Drop rows where the score is NaN (comme avant)
rows_before_drop = len(df_air_processed)
df_air_processed.dropna(subset=['pollution_score'], inplace=True)
rows_after_drop = len(df_air_processed)

print(f"Rows dropped due to unquantifiable score (NaN): {rows_before_drop - rows_after_drop}")
print(f"Air Quality Data - Shape after score cleanup: {df_air_processed.shape}")

# ... (le reste de la cellule : agrégation, etc.)

--- Quantification of Pollution Score ---
WARNING: 14 stations could not be assigned a pollution score.
These stations had the following text values:
['pas de données']

Stations with missing scores:
             station_name line_name pollution_level_text
103    Romainville-Carnot  Métro 11       pas de données
105  Saint-Denis - Pleyel  Métro 14       pas de données
128       Aéroport d'Orly  Métro 14       pas de données
194   Montreuil - Hôpital  Métro 11       pas de données
243      Serge Gainsbourg  Métro 11       pas de données
Rows dropped due to unquantifiable score (NaN): 14
Air Quality Data - Shape after score cleanup: (412, 7)

C:\Users\eva2p\AppData\Local\Temp\ipykernel_10900\3005765350.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_air_processed['pollution_score'] = df_air_processed['pollution_level_text'].str.lower().map(POLLUTION_SCORE_MAP)
C:\Users\eva2p\AppData\Local\Temp\ipykernel_10900\3005765350.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_air_processed.dropna(subset=['pollution_score'], inplace=True)

In [295]:
POLLUTION_SCORE_MAP = {
    'pollution faible': 1,
    'pollution moyenne': 2,
    'pollution élevée': 3,
}

In [296]:
df_air_processed['pollution_score'] = df_air_processed['pollution_level_text'].str.lower().map(POLLUTION_SCORE_MAP)
rows_with_nan_score = df_air_processed['pollution_score'].isna().sum()
df_air_processed.dropna(subset=['pollution_score'], inplace=True)

print(f"Rows dropped due to unquantifiable score (NaN): {rows_with_nan_score}")
print(f"Air Quality Data - Shape after score cleanup: {df_air_processed.shape}")

Rows dropped due to unquantifiable score (NaN): 0
Air Quality Data - Shape after score cleanup: (412, 7)

C:\Users\eva2p\AppData\Local\Temp\ipykernel_10900\4132144170.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_air_processed['pollution_score'] = df_air_processed['pollution_level_text'].str.lower().map(POLLUTION_SCORE_MAP)
C:\Users\eva2p\AppData\Local\Temp\ipykernel_10900\4132144170.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_air_processed.dropna(subset=['pollution_score'], inplace=True)

In [297]:
df_air_processed

,station_id,station_name,line_name,pollution_level_text,stop_lon_air,stop_lat_air,pollution_score
0,IDFM:463116,Abbesses,Métro 12,pollution faible,2.338395,48.884393,1
1,IDFM:483900,Aimé Césaire,Métro 12,pollution faible,2.378131,48.908438,1
3,IDFM:22130,Barbès - Rochechouart,Métro 4,pollution faible,2.349630,48.883402,1
4,IDFM:463019,Bastille,Métro 1,pollution moyenne,2.368693,48.851964,2
5,IDFM:463110,Belleville,Métro 11,pollution moyenne,2.376685,48.871990,2
...,...,...,...,...,...,...,...
654,IDFM:22164,Trocadéro,Métro 6,pollution moyenne,2.287625,48.863461,2
656,IDFM:462959,Vaneau,Métro 10,pollution moyenne,2.321351,48.848895,2
657,IDFM:463320,Varenne,Métro 13,pollution moyenne,2.314978,48.856624,2
658,IDFM:463321,Vaugirard,Métro 12,pollution faible,2.300978,48.839536,1
661,IDFM:463070,Wagram,Métro 3,pollution moyenne,2.304673,48.883846,2

In [298]:
df_air_processed.drop(columns=['pollution_level_text'], inplace=True)
df_air_processed

C:\Users\eva2p\AppData\Local\Temp\ipykernel_10900\412148941.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_air_processed.drop(columns=['pollution_level_text'], inplace=True)

,station_id,station_name,line_name,stop_lon_air,stop_lat_air,pollution_score
0,IDFM:463116,Abbesses,Métro 12,2.338395,48.884393,1
1,IDFM:483900,Aimé Césaire,Métro 12,2.378131,48.908438,1
3,IDFM:22130,Barbès - Rochechouart,Métro 4,2.349630,48.883402,1
4,IDFM:463019,Bastille,Métro 1,2.368693,48.851964,2
5,IDFM:463110,Belleville,Métro 11,2.376685,48.871990,2
...,...,...,...,...,...,...
654,IDFM:22164,Trocadéro,Métro 6,2.287625,48.863461,2
656,IDFM:462959,Vaneau,Métro 10,2.321351,48.848895,2
657,IDFM:463320,Varenne,Métro 13,2.314978,48.856624,2
658,IDFM:463321,Vaugirard,Métro 12,2.300978,48.839536,1
661,IDFM:463070,Wagram,Métro 3,2.304673,48.883846,2

In [299]:
def join_unique_lines(series):
    """Joins unique line names into a single string."""
    return ', '.join(series.dropna().astype(str).unique())

# 5. FINAL AGGREGATION: One average score per station_name (Ignoring station_id in groupby)
df_air_processed = df_air_processed.groupby(['station_name']).agg(
    
    # Calculate the mean pollution score
    pollution_score_mean=('pollution_score', 'mean'),
    
    # Correction: Use the join function to collect ALL line names for this station name
    lines_affected_air=('line_name', join_unique_lines),
    
    # Keep the first recorded coordinates and station ID (for reference, though ID may vary)
    station_id_list=('station_id', join_unique_lines), # Keep all IDs linked to this name
    stop_lat_air=('stop_lat_air', 'first'),
    stop_lon_air=('stop_lon_air', 'first')
).reset_index()


print(f"Final Air Quality Data (df_air_processed) shape: {df_air_processed.shape}")
print("\nCheck: Multi-Line Stations should now be merged:")
print(df_air_processed[['station_name', 'pollution_score_mean', 'lines_affected_air']].head())

Final Air Quality Data (df_air_processed) shape: (319, 6)

Check: Multi-Line Stations should now be merged:
      station_name  pollution_score_mean lines_affected_air
0         Abbesses                   1.0           Métro 12
1     Aimé Césaire                   1.0           Métro 12
2  Alexandre Dumas                   2.0            Métro 2
3   Alma - Marceau                   2.0            Métro 9
4           Alésia                   1.0            Métro 4

In [300]:
df_air_processed.head(15)

,station_name,pollution_score_mean,lines_affected_air,station_id_list,stop_lat_air,stop_lon_air
0,Abbesses,1.0,Métro 12,IDFM:463116,48.884393,2.338395
1,Aimé Césaire,1.0,Métro 12,IDFM:483900,48.908438,2.378131
2,Alexandre Dumas,2.0,Métro 2,IDFM:22122,48.856199,2.394591
3,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.864647,2.301104
4,Alésia,1.0,Métro 4,IDFM:463118,48.828152,2.327193
5,Anatole France,1.0,Métro 3,IDFM:22036,48.892207,2.284982
6,Anvers,2.0,Métro 2,IDFM:22123,48.882869,2.344155
7,Argentine,1.0,Métro 1,IDFM:463121,48.875667,2.289435
8,Arts et Métiers,1.5,"Métro 3, Métro 11","IDFM:21994, IDFM:21997",48.865535,2.356723
9,Asnières - Gennevilliers Les Courtilles,1.0,Métro 13,IDFM:22233,48.930604,2.284372
10,Assemblée Nationale,2.0,Métro 12,IDFM:463123,48.861122,2.320690
11,Auber,2.0,RER A,IDFM:monomodalStopPlace:45873,48.872349,2.329659
12,Aubervilliers-Pantin Quatre Chemins,2.0,Métro 7,IDFM:463031,48.903757,2.392221
13,Avenue Emile Zola,2.0,Métro 10,IDFM:463124,48.847038,2.295019
14,Avenue Foch,2.0,RER C,IDFM:monomodalStopPlace:45437,48.869853,2.274771

Join the two datasets

In [301]:
import unicodedata
import re

def normalize_station_name(name):
    """Removes accents, converts to lowercase, and removes punctuation/spaces."""
    if pd.isna(name):
        return name
    
    name = name.lower().strip()
    name = unicodedata.normalize('NFD', name)
    name = name.encode('ascii', 'ignore').decode('utf-8')
    name = re.sub(r'[^\w]', '', name).strip()
    return name

In [302]:
df_air_processed['station_name_clean'] = df_air_processed['station_name'].apply(normalize_station_name)
df_air_processed

,station_name,pollution_score_mean,lines_affected_air,station_id_list,stop_lat_air,stop_lon_air,station_name_clean
0,Abbesses,1.0,Métro 12,IDFM:463116,48.884393,2.338395,abbesses
1,Aimé Césaire,1.0,Métro 12,IDFM:483900,48.908438,2.378131,aimecesaire
2,Alexandre Dumas,2.0,Métro 2,IDFM:22122,48.856199,2.394591,alexandredumas
3,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.864647,2.301104,almamarceau
4,Alésia,1.0,Métro 4,IDFM:463118,48.828152,2.327193,alesia
...,...,...,...,...,...,...,...
314,Villiers,2.0,"Métro 3, Métro 2","IDFM:22027, IDFM:462988",48.881073,2.315815,villiers
315,Vincennes,2.0,RER A,IDFM:monomodalStopPlace:43224,48.847347,2.432584,vincennes
316,Volontaires,2.0,Métro 12,IDFM:22048,48.841412,2.307983,volontaires
317,Voltaire,2.0,Métro 9,IDFM:463325,48.857662,2.380032,voltaire
318,Wagram,2.0,Métro 3,IDFM:463070,48.883846,2.304673,wagram

In [303]:
df_gtfs_processed['station_name_clean'] = df_gtfs_processed['station_name'].apply(normalize_station_name)
df_gtfs_processed

,station_name,stop_lat,stop_lon,avg_passages,line_name,station_name_clean
0,1 route nationale,48.805000,1.774690,1.460000,"5332, 5338, 5342, 5367",1routenationale
1,10 arpents,49.040531,2.309446,2.129032,"1520, Navette, Soir",10arpents
2,11 novembre,48.880673,2.493969,11.655319,"221, 214, 3432, Soir, 114, 4531, 4534, 2, 612,...",11novembre
3,11 novembre - gare de coucelle-sur-yvette,48.703764,2.107537,4.636364,N122,11novembregaredecoucellesuryvette
4,11 novembre 1918,48.892935,2.465999,15.484429,"105, 143, 208, 308, N33, 181, 2304, 2302, 2374...",11novembre1918
...,...,...,...,...,...,...
13563,île saint-louis,48.851673,2.356322,11.578947,67,ilesaintlouis
13564,île verte,48.895978,2.163263,4.350000,"12, S3, T",ileverte
13565,île-de-france,48.685936,2.169871,14.973054,"4602, 4603, 4627, 4654, 203, 214, 303, 6533, 6...",iledefrance
13566,île-de-loisirs,49.022372,2.055395,7.486486,1207,iledeloisirs
13567,îles glénan,48.767394,1.926243,2.558140,"5121, 5123, 5190, 5124",ilesglenan

In [304]:
df_merged = pd.merge(
    df_air_processed,
    df_gtfs_processed,
    on='station_name_clean', 
    how='inner',
    # Add suffixes just in case, but 'stop_lat' and 'stop_lon' are only in GTFS side now
    suffixes=('_air', '_gtfs') 
)

In [305]:
print(f"Merge successful: {df_merged.shape[0]} stations were successfully matched.")

Merge successful: 348 stations were successfully matched.

In [306]:
df_merged

,station_name_air,pollution_score_mean,lines_affected_air,station_id_list,stop_lat_air,stop_lon_air,station_name_clean,station_name_gtfs,stop_lat,stop_lon,avg_passages,line_name
0,Abbesses,1.0,Métro 12,IDFM:463116,48.884393,2.338395,abbesses,abbesses,48.875003,2.581553,32.893204,"9, 9s, 12, 40"
1,Aimé Césaire,1.0,Métro 12,IDFM:483900,48.908438,2.378131,aimecesaire,aimé césaire,48.908438,2.378131,32.398496,"12, 139, 35, N43"
2,Alexandre Dumas,2.0,Métro 2,IDFM:22122,48.856199,2.394591,alexandredumas,alexandre dumas,48.740574,2.446792,20.572770,"450, 1511, 337, 2, 111, 30-07, CitéVal S, 322"
3,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.864647,2.301104,almamarceau,alma - marceau,48.864728,2.301131,33.280851,"9, 42, 80, 63, 92, 72"
4,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.864647,2.301104,almamarceau,alma marceau,48.865014,2.300745,26.909091,BUSM09
...,...,...,...,...,...,...,...,...,...,...,...,...
343,Villiers,2.0,"Métro 3, Métro 2","IDFM:22027, IDFM:462988",48.881073,2.315815,villiers,villiers,48.896109,2.272925,38.657895,"93, 3, 2, N16, N52, 30, 4579"
344,Vincennes,2.0,RER A,IDFM:monomodalStopPlace:43224,48.847347,2.432584,vincennes,vincennes,48.847347,2.432584,218.800000,A
345,Volontaires,2.0,Métro 12,IDFM:22048,48.841412,2.307983,volontaires,volontaires,48.841412,2.307983,67.595238,12
346,Voltaire,2.0,Métro 9,IDFM:463325,48.857662,2.380032,voltaire,voltaire,48.693443,2.148869,18.189280,"4660, 370, 9, 262, 272, N24, 146, 263, 111, 14..."
347,Wagram,2.0,Métro 3,IDFM:463070,48.883846,2.304673,wagram,wagram,48.883761,2.304625,42.516129,"3, 2, 12, 60"

In [307]:
cols_to_keep = [
    'station_name_air',
    'pollution_score_mean',
    'lines_affected_air',
    'station_id_list',
    'stop_lat',
    'stop_lon',
    'avg_passages',
]
df_merged = df_merged[cols_to_keep]
df_merged

,station_name_air,pollution_score_mean,lines_affected_air,station_id_list,stop_lat,stop_lon,avg_passages
0,Abbesses,1.0,Métro 12,IDFM:463116,48.875003,2.581553,32.893204
1,Aimé Césaire,1.0,Métro 12,IDFM:483900,48.908438,2.378131,32.398496
2,Alexandre Dumas,2.0,Métro 2,IDFM:22122,48.740574,2.446792,20.572770
3,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.864728,2.301131,33.280851
4,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.865014,2.300745,26.909091
...,...,...,...,...,...,...,...
343,Villiers,2.0,"Métro 3, Métro 2","IDFM:22027, IDFM:462988",48.896109,2.272925,38.657895
344,Vincennes,2.0,RER A,IDFM:monomodalStopPlace:43224,48.847347,2.432584,218.800000
345,Volontaires,2.0,Métro 12,IDFM:22048,48.841412,2.307983,67.595238
346,Voltaire,2.0,Métro 9,IDFM:463325,48.693443,2.148869,18.189280
347,Wagram,2.0,Métro 3,IDFM:463070,48.883761,2.304625,42.516129

In [308]:
df_merged.rename(columns={'station_name_air': 'station_name', 'lines_affected_air': 'lines_affected', 'stop_lat': 'latitude', 'stop_lon': 'longitude'}, inplace=True)
df_merged

C:\Users\eva2p\AppData\Local\Temp\ipykernel_10900\1274607319.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged.rename(columns={'station_name_air': 'station_name', 'lines_affected_air': 'lines_affected', 'stop_lat': 'latitude', 'stop_lon': 'longitude'}, inplace=True)

,station_name,pollution_score_mean,lines_affected,station_id_list,latitude,longitude,avg_passages
0,Abbesses,1.0,Métro 12,IDFM:463116,48.875003,2.581553,32.893204
1,Aimé Césaire,1.0,Métro 12,IDFM:483900,48.908438,2.378131,32.398496
2,Alexandre Dumas,2.0,Métro 2,IDFM:22122,48.740574,2.446792,20.572770
3,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.864728,2.301131,33.280851
4,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.865014,2.300745,26.909091
...,...,...,...,...,...,...,...
343,Villiers,2.0,"Métro 3, Métro 2","IDFM:22027, IDFM:462988",48.896109,2.272925,38.657895
344,Vincennes,2.0,RER A,IDFM:monomodalStopPlace:43224,48.847347,2.432584,218.800000
345,Volontaires,2.0,Métro 12,IDFM:22048,48.841412,2.307983,67.595238
346,Voltaire,2.0,Métro 9,IDFM:463325,48.693443,2.148869,18.189280
347,Wagram,2.0,Métro 3,IDFM:463070,48.883761,2.304625,42.516129

In [309]:
df_merged = df_merged.drop_duplicates(subset=['station_name'])
df_merged

,station_name,pollution_score_mean,lines_affected,station_id_list,latitude,longitude,avg_passages
0,Abbesses,1.0,Métro 12,IDFM:463116,48.875003,2.581553,32.893204
1,Aimé Césaire,1.0,Métro 12,IDFM:483900,48.908438,2.378131,32.398496
2,Alexandre Dumas,2.0,Métro 2,IDFM:22122,48.740574,2.446792,20.572770
3,Alma - Marceau,2.0,Métro 9,IDFM:463052,48.864728,2.301131,33.280851
5,Alésia,1.0,Métro 4,IDFM:463118,48.828201,2.327093,86.255814
...,...,...,...,...,...,...,...
343,Villiers,2.0,"Métro 3, Métro 2","IDFM:22027, IDFM:462988",48.896109,2.272925,38.657895
344,Vincennes,2.0,RER A,IDFM:monomodalStopPlace:43224,48.847347,2.432584,218.800000
345,Volontaires,2.0,Métro 12,IDFM:22048,48.841412,2.307983,67.595238
346,Voltaire,2.0,Métro 9,IDFM:463325,48.693443,2.148869,18.189280
347,Wagram,2.0,Métro 3,IDFM:463070,48.883761,2.304625,42.516129

In [310]:
#export to CSV
df_merged.to_csv("data/merged_air_gtfs.csv", index=False)

PermissionError: [Errno 13] Permission denied: 'data/merged_air_gtfs.csv'